# Generated by Django 4.2 on 2024-06-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.IntegerField(choices=[(1, '08:00-10:00'), (2, '10:00-12:00'), (3, '14:00-16:00'), (4, '16:00-18:00'), (5, '18:00-20:00')], unique=True)),
            ],
        ),
    ]
